tavola-helm-chart:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10    

  updateStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate

  containersCommand:
  - command:
    - bin/sqs-integration
  
  configMapRed:
    enabled: true
    
  secretRef:
    enabled: true

  containerPorts:
    enabled: false
  
  image:
   repository: 714177237676.dkr.ecr.us-east-1.amazonaws.com/sqs-integration
   tag: main
   imagePullPolicy: Always

  livenessProbe:
    enabled: false

  readinessProbe:
    enabled: false

  resources:
    limits:
      cpu: 50m
      memory: 250Mi
    requests:
      cpu: 10m
      memory: 100Mi

  nodeSelector:
    enabled: true
    ng: general
    vmtype: application

  volumeMounts: {}
  volumes: {}

  service:
    enabled: false
