{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- template "labels" . }} 
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
  - name: http
    port: {{ .Values.service.ports.http }}
    protocol: TCP
    targetPort: {{ .Values.service.targerPort }}
  selector:
    run: {{ .Release.Name }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  type: {{ .Values.service.type }}
{{- end }}