apiVersion: v2
name: new-service
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
- name: tavola-helm-chart
  version: 0.1.0
  repository: file://../../chart-microservice/tavola-helm-chart
