tavola-helm-chart:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10    

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate

  containersCommand:
  - command:
      - bundle
      - exec
      - puma
      - -C
      - config/puma.rb
  image:
   repository: 714177237676.dkr.ecr.us-east-1.amazonaws.com/pdf2png-server
   tag: main
   imagePullPolicy: Always

  livenessProbe:
    httpGet:
      path: "/healthcheck"
      port: 3000
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 10
    failureThreshold: 3

  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /healthcheck
      port: 3000
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5

  resources:
    limits:
      cpu: "8"
      memory: 4Gi
    requests:
      cpu: "4"
      memory: 2560Mi

  nodeSelector:
    enabled: true
    ng: general
    vmtype: application

  volumeMounts: {}
  volumes: {}