tavola-helm-chart:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10    

  updateStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate

  containersCommand:
  - command:
      - /app/bin/cert-validator

  secretRef:
    enabled: true

  containerPort: 7000
  protocol: "TCP"
  
  image:
   repository: 714177237676.dkr.ecr.us-east-1.amazonaws.com/cert-validator
   tag: main
   imagePullPolicy: Always

  livenessProbe:
    httpGet:
      path: /healthcheck
      port: 7000
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 10
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /healthcheck
      port: 7000
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5

  resources:
    limits:
      cpu: 100m
      memory: 1536Mi
    requests:
      cpu: 10m
      memory: 500Mi

  nodeSelector:
    enabled: true
    ng: general
    vmtype: application

  volumeMounts: {}
  volumes: {}

  service:
    enabled: true
    ports:
      http: 80
    targerPort: 7000
    type: ClusterIP  
    sessionAffinity: None