setLabels:
  labels: merlin

labelType: run

progressDeadlineSeconds: 600
replicas: 1
revisionHistoryLimit: 10    

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

containersCommand:
  command:
    - node
    - build/server.js    

containerName: merlin
  
configMapRef:
  enabled: true
  name: env-merlin
  
secretRef:
  enabled: true
  name: merlin

containerPorts:
- containerPort: 3000
  protocol: "TCP"
  
image:
  repository: clicksign/merlin
  tag: v1.7.0
  imagePullPolicy: Always

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /healthcheck
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /healthcheck
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 500Mi

nodeSelector:
  enabled: true
  ng: general
  vmtype: application

volumeMounts: {}
volumes: {}

service:
  enabled: true
  name: merlin
  ports:
    http: 80
  targerPort: 3000
  type: ClusterIP  
  sessionAffinity: None

autoscaling:
  enabled: false

lifecycle:
  enabled: false
