apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: signature-service
    meta.helm.sh/release-namespace: helm
  creationTimestamp: "2022-06-08T18:26:30Z"
  generation: 1
  labels:
    app: signature-service
    app.kubernetes.io/managed-by: Helm
    tier: queue
  name: signature-service
  namespace: helm
  resourceVersion: "259672816"
  selfLink: /apis/apps/v1/namespaces/helm/deployments/signature-service
  uid: 8ff830b6-b3f0-4d9f-a148-b5bc3fa5ddf0
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: signature-service
      tier: queue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: signature-service
        tier: queue
      name: signature-service
    spec:
      containers:
      - command:
        - /app/docker-entrypoint.sh
        envFrom:
        - configMapRef:
            name: env-signature-service
        - secretRef:
            name: signature-service
        image: 714177237676.dkr.ecr.us-east-1.amazonaws.com/signature-service:main
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 7000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: signature-service
        ports:
        - containerPort: 7000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 7000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 2560Mi
          requests:
            cpu: 500m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/pki-license
          name: pki-license
          readOnly: true
        - mountPath: /app/src/main/resources
          name: certificates
          readOnly: true
        - mountPath: /app/aspose-license
          name: aspose-license
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        ng: general
        vmtype: application
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificates
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: certificate.pem
                mode: 420
                path: certificate.pem
              name: lacuna-certificate-pem
          - configMap:
              items:
              - key: certificate.p12
                mode: 420
                path: certificate.p12
              name: lacuna-certificate-p12
      - name: pki-license
        secret:
          defaultMode: 420
          items:
          - key: LacunaPkiLicense.config
            path: LacunaPkiLicense.config
          secretName: lacuna-pki-license
      - name: aspose-license
        secret:
          defaultMode: 420
          items:
          - key: Aspose.PDF.Java.lic
            path: Aspose.PDF.Java.lic
          secretName: aspose-license
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-06-08T18:26:43Z"
    lastUpdateTime: "2022-06-08T18:26:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-06-08T18:26:30Z"
    lastUpdateTime: "2022-06-08T18:26:43Z"
    message: ReplicaSet "signature-service-c67c69c6f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
