tavola-helm-chart:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10    

  updateStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate

  containersCommand:
  - command:
      - /app/docker-entrypoint.sh

  secretRef:
    enabled: true

  containerPort: 7000
  protocol: "TCP"
  
  image:
   repository: 714177237676.dkr.ecr.us-east-1.amazonaws.com/signature-service
   tag: main
   imagePullPolicy: Always

  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /healthcheck
      port: 7000
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
    
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /healthcheck
      port: 7000
      scheme: HTTP 
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
    
  resources:
    limits:
      cpu: "1"
      memory: 2560Mi
    requests:
      cpu: 500m
      memory: 2Gi

  nodeSelector:
    enabled: true
    ng: general
    vmtype: application

  volumeMounts:
  - mountPath: /app/pki-license
    name: pki-license
    readOnly: true
  - mountPath: /app/src/main/resources
    name: certificates
    readOnly: true
  - mountPath: /app/aspose-license
    name: aspose-license
    readOnly: true
  volumes:
  - name: certificates
    projected:
      defaultMode: 420
      sources:
      - secret:
          items:
          - key: certificate.pem
            mode: 420
            path: certificate.pem
          name: lacuna-certificate-pem
      - configMap:
          items:
          - key: certificate.p12
            mode: 420
            path: certificate.p12
          name: lacuna-certificate-p12
  - name: pki-license
    secret:
      defaultMode: 420
      items:
      - key: LacunaPkiLicense.config
        path: LacunaPkiLicense.config
      secretName: lacuna-pki-license
  - name: aspose-license
    secret:
      defaultMode: 420
      items:
      - key: Aspose.PDF.Java.lic
        path: Aspose.PDF.Java.lic
      secretName: aspose-license 

  service:
    enabled: true
    ports:
      http: 80
    targerPort: 7000
    type: ClusterIP  
    sessionAffinity: None