name: Helm Package and S3 Bucket Upload

on:
  push:
    branches:
      - main
      - new-microservice
jobs:
  build:
    name: Helm Package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
        
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0
      
      - name: Set up Helm S3 Plugin
        run: helm plugin install https://github.com/hypnoglow/helm-s3.git
      
      - name: Execute Helm Package
        run: helm package charts
        
      - name: Helm Repo Add
        run: helm repo add main-chart s3://my-helm-repo-lab1/v1
      
      - name: S3 package push
        run: |
          file=$(ls | grep .tgz)
          helm s3 push $file main-chart
      
      - name: Define TAG
        id: tag
        run: echo "::set-output name=tag-name::$(tag=$(sed -n '/^version:/p' charts/Chart.yaml))"

      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.tag.outputs.tag-name }}

