name: Helm Package and S3 Bucket Upload

on:
  push:
    branches:
      - main
      - new-microservice
jobs:
  build:
    name: Chart release
    runs-on: ubuntu-latest
    steps:
      - name: Package stable charts
        uses: flydiverny/helm-package-action@master
        with:
          args: ./charts

