name: Lint and Test Charts

on:
  push:
    branches:
      - new-microservice
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: GitHub Action for Helm Templates Validation
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/
          CHART_VALUES: ./charts/values.yaml


